name: Legal Advice OneSignal Rate Notifications

on:
  schedule:
    # Run at 3 PM IST (UTC+5:30)
    # 9:30 AM UTC (3 PM IST)
    - cron: '30 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run notification script
        env:
          LEGAL_ADVICE_ONESIGNAL_APP_ID: ${{ secrets.LEGAL_ADVICE_ONESIGNAL_APP_ID }}
          LEGAL_ADVICE_ONESIGNAL_API_KEY: ${{ secrets.LEGAL_ADVICE_ONESIGNAL_API_KEY }}
        run: python legal_advice_onesignal.py
